import 'dart:async';

import 'package:ffmpeg_kit_flutter_new_full/ffprobe_kit.dart';
import 'package:ffmpeg_kit_flutter_new_full/session.dart';

// Central FFmpeg facade for the app.
//
// Generated by:
//   dart run tool/switch_ffmpeg_backend.dart new_full

export 'package:ffmpeg_kit_flutter_new_full/ffmpeg_kit.dart';
export 'package:ffmpeg_kit_flutter_new_full/ffprobe_kit.dart';
export 'package:ffmpeg_kit_flutter_new_full/log.dart';
export 'package:ffmpeg_kit_flutter_new_full/return_code.dart';
export 'package:ffmpeg_kit_flutter_new_full/session.dart';

Future<Session> executeQuietFfprobe(String command) async {
  final completer = Completer<Session>();
  await FFprobeKit.executeAsync(
    command,
    (session) {
      if (!completer.isCompleted) {
        completer.complete(session);
      }
    },
    (_) {},
  );
  return completer.future;
}
