import os

BILLING_EVENTS_TABLE = os.environ["BILLING_EVENTS_TABLE"]
SUBSCRIPTIONS_TABLE = os.environ["SUBSCRIPTIONS_TABLE"]
ENTITLEMENTS_TABLE = os.environ["ENTITLEMENTS_TABLE"]
CATALOG_MAPPINGS_TABLE = os.environ["CATALOG_MAPPINGS_TABLE"]
CUSTOMER_LINKS_TABLE = os.environ["CUSTOMER_LINKS_TABLE"]
PURCHASE_TOKENS_TABLE = os.environ["PURCHASE_TOKENS_TABLE"]
RECONCILIATION_JOBS_TABLE = os.environ["RECONCILIATION_JOBS_TABLE"]
PROJECTION_QUEUE_URL = os.environ["PROJECTION_QUEUE_URL"]

ENFORCE_SUBSCRIPTIONS = os.environ.get("ENFORCE_SUBSCRIPTIONS", "false").lower() == "true"
ALLOW_STUDIO_TIER = os.environ.get("ALLOW_STUDIO_TIER", "false").lower() == "true"

DEFAULT_CHECKOUT_URL = os.environ.get(
    "DEFAULT_CHECKOUT_URL",
    "https://www.mixroom.ai/subscribe",
)
