import 'dart:io';

const _newFull = 'new_full';
const _compat16kb = '16kb';

const _pubspecPath = 'pubspec.yaml';
const _facadePath = 'lib/ffmpeg/ffmpeg.dart';

const _newFullDependency = '  ffmpeg_kit_flutter_new_full: ^1.2.0';
const _compat16kbDependency = '  ffmpeg_kit_16kb: ^1.0.4';
const _newFullComment = '  # ffmpeg_kit_flutter_new_full: ^1.2.0';
const _compat16kbComment = '  # ffmpeg_kit_16kb: ^1.0.4';

void main(List<String> args) {
  if (args.length != 1 ||
      (args.first != _newFull && args.first != _compat16kb)) {
    stderr.writeln(
        'Usage: dart run tool/switch_ffmpeg_backend.dart <new_full|16kb>');
    exitCode = 64;
    return;
  }

  final backend = args.first;
  _switchPubspec(backend);
  _writeFacade(backend);

  stdout.writeln('Switched FFmpeg backend to $backend.');
  stdout.writeln('Next: flutter pub get');
}

void _switchPubspec(String backend) {
  final file = File(_pubspecPath);
  var content = file.readAsStringSync();

  content = content
      .replaceAll(_newFullDependency, _newFullComment)
      .replaceAll(_compat16kbDependency, _compat16kbComment)
      .replaceAll(_newFullComment, _newFullComment)
      .replaceAll(_compat16kbComment, _compat16kbComment);

  if (backend == _newFull) {
    content = content.replaceFirst(_newFullComment, _newFullDependency);
  } else {
    content = content.replaceFirst(_compat16kbComment, _compat16kbDependency);
  }

  file.writeAsStringSync(content);
}

void _writeFacade(String backend) {
  final package =
      backend == _newFull ? 'ffmpeg_kit_flutter_new_full' : 'ffmpeg_kit_16kb';
  final content = '''
// Central FFmpeg facade for the app.
//
// Generated by:
//   dart run tool/switch_ffmpeg_backend.dart $backend

export 'package:$package/ffmpeg_kit.dart';
export 'package:$package/ffprobe_kit.dart';
export 'package:$package/log.dart';
export 'package:$package/return_code.dart';
export 'package:$package/session.dart';
''';

  File(_facadePath).writeAsStringSync(content);
}
