#pragma once

#define JUCE_GLOBAL_MODULE_SETTINGS_INCLUDED 1
#define JUCE_IOS 1
#define JUCE_PLUGINHOST_AU 1
#define JUCE_USE_CURL 0
#define JUCE_WEB_BROWSER 0
#define JUCE_USE_CAMERA 0
#define JUCE_DONT_DECLARE_PROJECTINFO 1
#define JUCE_MODAL_LOOPS_PERMITTED 1
#define JUCE_STRICT_REFCOUNTEDPOINTER 1
